#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the vllm-ascend project.
#

FROM quay.io/ascend/cann:9.0.1-950-openeuler24.03-py3.12

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

WORKDIR /workspace

SHELL ["/bin/bash", "-c"]

# Install clang (for triton-ascend) and Mooncake
ARG MOONCAKE_TAG=0.3.11.post1
RUN yum update -y && \
    yum install -y git vim wget net-tools gcc gcc-c++ make cmake numactl numactl-devel libibverbs-devel jemalloc hiredis-devel clang patch && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    python3 -m pip install mooncake-transfer-engine-npu==${MOONCAKE_TAG} --extra-index-url https://mirrors.aliyun.com/pypi/web/simple && \
    rm -rf /var/cache/yum/*

# Install modelscope (for fast download) and ray (for multinode)
RUN pip config set global.index-url ${PIP_INDEX_URL} && \
    python3 -m pip install modelscope 'ray>=2.47.1,<=2.48.0' 'protobuf>3.20.0' && \
    python3 -m pip cache purge

# Install vLLM
ARG VLLM_REPO=https://github.com/vllm-project/vllm.git
ARG VLLM_TAG=v0.23.0
RUN git clone --depth 1 -b $VLLM_TAG $VLLM_REPO /vllm-workspace/vllm
# In x86, triton will be installed by vllm. But in Ascend, triton doesn't work correctly. we need to uninstall it.
RUN VLLM_TARGET_DEVICE="empty" python3 -m pip install -e /vllm-workspace/vllm/[audio] --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton && \
    python3 -m pip cache purge

# Install vllm-ascend
ARG SOC_VERSION="ascend950dt_9582"
ARG COMPILE_CUSTOM_KERNELS=1
ENV SOC_VERSION=$SOC_VERSION \
    TASK_QUEUE_ENABLE=1 \
    OMP_NUM_THREADS=1
COPY . /vllm-workspace/vllm-ascend/

RUN export PIP_EXTRA_INDEX_URL="https://mirrors.huaweicloud.com/ascend/repos/pypi" && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    python3 -m pip install -e /vllm-workspace/vllm-ascend/ --extra-index https://download.pytorch.org/whl/cpu/ && \
    python3 -m pip uninstall -y triton triton-ascend && \
    python3 -m pip install triton-ascend==3.2.1 --extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi && \
    python3 -m pip cache purge

# Install prebuilt CANN custom operators (KeyPool / PoolKeyIndexer for GLM) and the Python wrapper wheel
RUN source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    export ASCEND_OPP_PATH=${ASCEND_OPP_PATH:-${ASCEND_HOME_PATH}/opp} && \
    if [ "$(uname -m)" = "aarch64" ]; then OP_PKG_DIR="arm"; else OP_PKG_DIR="x86"; fi && \
    OP_RUN_PKG=$(ls /vllm-workspace/vllm-ascend/operator/${OP_PKG_DIR}/a5/cann-ops-transformer-custom_linux-*.run) && \
    bash "${OP_RUN_PKG}" && \
    ls ${ASCEND_OPP_PATH}/vendors/custom_transformer/op_api/lib && \
    python3 -m pip install ninja && \
    python3 -m pip install /vllm-workspace/vllm-ascend/operator/${OP_PKG_DIR}/wheel/cann_ops_transformer-1.0.0-py3-none-any.whl && \
    ln -sfn "$(readlink -f ${ASCEND_OPP_PATH})/vendors/custom_transformer" /usr/local/Ascend/custom_transformer_ops && \
    echo "/usr/local/Ascend/custom_transformer_ops/op_api/lib" > /etc/ld.so.conf.d/custom-transformer.conf && \
    ldconfig && \
    python3 -c "import importlib.util as _iu; _s = _iu.spec_from_file_location('cann_kpool_loader', '/vllm-workspace/vllm-ascend/vllm_ascend/ops/cann_kpool_loader.py'); _m = _iu.module_from_spec(_s); _s.loader.exec_module(_m); import cann_ops_transformer.ops.pool_key_indexer as _pki; _pki.pool_key_indexer_op_builder.load(verbose=False); print('[custom-ops] pool_key_indexer torch extension prebuilt')" && \
    python3 -m pip cache purge

# Expose the prebuilt custom operators to CANN and the dynamic linker at runtime
ENV LD_LIBRARY_PATH=/usr/local/Ascend/custom_transformer_ops/op_api/lib:${LD_LIBRARY_PATH} \
    ASCEND_CUSTOM_OPP_PATH=/usr/local/Ascend/custom_transformer_ops

RUN echo "export LD_PRELOAD=/usr/lib64/libjemalloc.so.2:$LD_PRELOAD" >> ~/.bashrc
RUN echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib" >> ~/.bashrc

CMD ["/bin/bash"]
